export const person={
   text:"人物",
   list:[
    {
      path:require("./assets/images/person/1_smile.png"),
      key:"smile"
    },
    {
      path:require("./assets/images/person/3_grinning.png"),
      key:"grinning"
    },
    {
      path:require("./assets/images/person/4_blush.png"),
      key:"blush"
    },
    {
      path:require("./assets/images/person/6_wink.png"),
      key:"wink"
    },
    {
      path:require("./assets/images/person/7_heart_eyes.png"),
      key:"heart_eyes"
    },
    {
      path:require("./assets/images/person/8_kissing_heart.png"),
      key:"kissing_heart"
    },
    {
      path:require("./assets/images/person/9_kissing_closed_eyes.png"),
      key:"kissing_closed_eyes"
    },
    {
      path:require("./assets/images/person/10_disappointed.png"),
      key:"disappointed"
    },
    {
      path:require("./assets/images/person/10_kissing.png"),
      key:"kissing"
    },
    {
      path:require("./assets/images/person/11_kissing_smiling_eyes.png"),
      key:"kissing_smiling_eyes"
    },
    {
      path:require("./assets/images/person/12_stuck_out_tongue_winking_eye.png"),
      key:"stuck_out_tongue_winking_eye"
    },
    {
      path:require("./assets/images/person/13_stuck_out_tongue_closed_eyes.png"),
      key:"13_stuck_out_tongue_closed_eyes"
    },
    {
      path:require("./assets/images/person/14_stuck_out_tongue.png"),
      key:"14_stuck_out_tongue"
    },
    {
      path:require("./assets/images/person/15_flushed.png"),
      key:"15_flushed"
    },
    {
      path:require("./assets/images/person/16_grin.png"),
      key:"16_grin"
    },
    {
      path:require("./assets/images/person/17_pensive.png"),
      key:"17_pensive"
    },
    {
      path:require("./assets/images/person/18_relieved.png"),
      key:"18_relieved"
    },
    {
      path:require("./assets/images/person/19_unamused.png"),
      key:"19_unamused"
    },
    {
      path:require("./assets/images/person/20_fearful.png"),
      key:"20_fearful"
    },
    {
      path:require("./assets/images/person/20_persevere.png"),
      key:"20_persevere"
    },
 
    {
      path:require("./assets/images/person/22_joy.png"),
      key:"22_joy"
    },
    {
      path:require("./assets/images/person/23_sob.png"),
      key:"23_sob"
    },
    {
      path:require("./assets/images/person/24_sleepy.png"),
      key:"24_sleepy"
    },
    {
      path:require("./assets/images/person/25_cold_sweat.png"),
      key:"25_cold_sweat"
    },
    {
      path:require("./assets/images/person/25_disappointed_relieved.png"),
      key:"25_disappointed_relieved"
    },
    {
      path:require("./assets/images/person/26_sweat_smile.png"),
      key:"26_sweat_smile"
    },
    {
      path:require("./assets/images/person/27_sweat.png"),
      key:"27_sweat"
    },
    {
      path:require("./assets/images/person/28_weary.png"),
      key:"28_weary"
    },
    {
      path:require("./assets/images/person/29_tired_face.png"),
      key:"29_tired_face"
    },
    {
      path:require("./assets/images/person/30_scream.png"),
      key:"30_scream"
    },
    {
      path:require("./assets/images/person/31_angry.png"),
      key:"31_angry"
    },
    {
      path:require("./assets/images/person/32_rage.png"),
      key:"32_rage"
    },
    {
      path:require("./assets/images/person/33_triumph.png"),
      key:"33_triumph"
    },
    {
      path:require("./assets/images/person/34_laughing.png"),
      key:"34_laughing"
    },
    {
      path:require("./assets/images/person/35_yum.png"),
      key:"35_yum"
    },
    {
      path:require("./assets/images/person/36_mask.png"),
      key:"36_mask"
    },
    {
      path:require("./assets/images/person/37_sunglasses.png"),
      key:"37_sunglasses"
    },
    {
      path:require("./assets/images/person/38_sleeping.png"),
      key:"38_sleeping"
    },
    {
      path:require("./assets/images/person/39_dizzy_face.png"),
      key:"39_dizzy_face"
    },
    {
      path:require("./assets/images/person/40_astonished.png"),
      key:"40_astonished"
    },
    {
      path:require("./assets/images/person/41_worried.png"),
      key:"41_worried"
    },
    {
      path:require("./assets/images/person/42_frowning.png"),
      key:"42_frowning"
    },
    {
      path:require("./assets/images/person/43_anguished.png"),
      key:"43_anguished"
    },
    {
      path:require("./assets/images/person/44_neutral_face.png"),
      key:"44_neutral_face"
    },
    {
      path:require("./assets/images/person/45_confused.png"),
      key:"45_confused"
    },
    {
      path:require("./assets/images/person/46_no_mouth.png"),
      key:"46_no_mouth"
    },
    {
      path:require("./assets/images/person/47_innocent.png"),
      key:"47_innocent"
    },
    {
      path:require("./assets/images/person/48_smirk.png"),
      key:"48_smirk"
    },
    {
      path:require("./assets/images/person/49_expressionless.png"),
      key:"49_expressionless"
    }
  ]
}