const pathStr="https://raw.githubusercontent.com/MTTTM/vue-keyboard-cn/main/src/dev/assets/images/";
export const person={
   text:"人物",
   list:[
    {
      path:`${pathStr}/person/1_smile.png`,
      key:"smile"
    },
    {
      path:`${pathStr}/person/3_grinning.png`,
      key:"grinning"
    },
    {
      path:`${pathStr}/person/4_blush.png`,
      key:"blush"
    },
    {
      path:`${pathStr}/person/6_wink.png`,
      key:"wink"
    },
    {
      path:`${pathStr}/person/7_heart_eyes.png`,
      key:"heart_eyes"
    },
    {
      path:`${pathStr}/person/8_kissing_heart.png`,
      key:"kissing_heart"
    },
    {
      path:`${pathStr}/person/9_kissing_closed_eyes.png`,
      key:"kissing_closed_eyes"
    },
    {
      path:`${pathStr}/person/10_disappointed.png`,
      key:"disappointed"
    },
    {
      path:`${pathStr}/person/10_kissing.png`,
      key:"kissing"
    },
    {
      path:`${pathStr}/person/11_kissing_smiling_eyes.png`,
      key:"kissing_smiling_eyes"
    },
    {
      path:`${pathStr}/person/12_stuck_out_tongue_winking_eye.png`,
      key:"stuck_out_tongue_winking_eye"
    },
    {
      path:`${pathStr}/person/13_stuck_out_tongue_closed_eyes.png`,
      key:"13_stuck_out_tongue_closed_eyes"
    },
    {
      path:`${pathStr}/person/14_stuck_out_tongue.png`,
      key:"14_stuck_out_tongue"
    },
    {
      path:`${pathStr}/person/15_flushed.png`,
      key:"15_flushed"
    },
    {
      path:`${pathStr}/person/16_grin.png`,
      key:"16_grin"
    },
    {
      path:`${pathStr}/person/17_pensive.png`,
      key:"17_pensive"
    },
    {
      path:`${pathStr}/person/18_relieved.png`,
      key:"18_relieved"
    },
    {
      path:`${pathStr}/person/19_unamused.png`,
      key:"19_unamused"
    },
    {
      path:`${pathStr}/person/20_fearful.png`,
      key:"20_fearful"
    },
    {
      path:`${pathStr}/person/20_persevere.png`,
      key:"20_persevere"
    },
 
    {
      path:`${pathStr}/person/22_joy.png`,
      key:"22_joy"
    },
    {
      path:`${pathStr}/person/23_sob.png`,
      key:"23_sob"
    },
    {
      path:`${pathStr}/person/24_sleepy.png`,
      key:"24_sleepy"
    },
    {
      path:`${pathStr}/person/25_cold_sweat.png`,
      key:"25_cold_sweat"
    },
    {
      path:`${pathStr}/person/25_disappointed_relieved.png`,
      key:"25_disappointed_relieved"
    },
    {
      path:`${pathStr}/person/26_sweat_smile.png`,
      key:"26_sweat_smile"
    },
    {
      path:`${pathStr}/person/27_sweat.png`,
      key:"27_sweat"
    },
    {
      path:`${pathStr}/person/28_weary.png`,
      key:"28_weary"
    },
    {
      path:`${pathStr}/person/29_tired_face.png`,
      key:"29_tired_face"
    },
    {
      path:`${pathStr}/person/30_scream.png`,
      key:"30_scream"
    },
    {
      path:`${pathStr}/person/31_angry.png`,
      key:"31_angry"
    },
    {
      path:`${pathStr}/person/32_rage.png`,
      key:"32_rage"
    },
    {
      path:`${pathStr}/person/33_triumph.png`,
      key:"33_triumph"
    },
    {
      path:`${pathStr}/person/34_laughing.png`,
      key:"34_laughing"
    },
    {
      path:`${pathStr}/person/35_yum.png`,
      key:"35_yum"
    },
    {
      path:`${pathStr}/person/36_mask.png`,
      key:"36_mask"
    },
    {
      path:`${pathStr}/person/37_sunglasses.png`,
      key:"37_sunglasses"
    },
    {
      path:`${pathStr}/person/38_sleeping.png`,
      key:"38_sleeping"
    },
    {
      path:`${pathStr}/person/39_dizzy_face.png`,
      key:"39_dizzy_face"
    },
    {
      path:`${pathStr}/person/40_astonished.png`,
      key:"40_astonished"
    },
    {
      path:`${pathStr}/person/41_worried.png`,
      key:"41_worried"
    },
    {
      path:`${pathStr}/person/42_frowning.png`,
      key:"42_frowning"
    },
    {
      path:`${pathStr}/person/43_anguished.png`,
      key:"43_anguished"
    },
    {
      path:`${pathStr}/person/44_neutral_face.png`,
      key:"44_neutral_face"
    },
    {
      path:`${pathStr}/person/45_confused.png`,
      key:"45_confused"
    },
    {
      path:`${pathStr}/person/46_no_mouth.png`,
      key:"46_no_mouth"
    },
    {
      path:`${pathStr}/person/47_innocent.png`,
      key:"47_innocent"
    },
    {
      path:`${pathStr}/person/48_smirk.png`,
      key:"48_smirk"
    },
    {
      path:`${pathStr}/person/49_expressionless.png`,
      key:"49_expressionless"
    }
  ]
}
export const hearts={
  text:"有爱",
  list:[
    {
      path:`${pathStr}/hearts/1_yellow_heart.png`,
      key:"1_yellow_heart"
    },
    {
      path:`${pathStr}/hearts/2_blue_heart.png`,
      key:"2_blue_heart"
    },
    {
      path:`${pathStr}/hearts/3_purple_heart.png`,
      key:"3_purple_heart"
    },
    {
      path:`${pathStr}/hearts/4_green_heart.png`,
      key:"4_green_heart"
    },
    {
      path:`${pathStr}/hearts/5_heart.png`,
      key:"5_heart"
    },
    {
      path:`${pathStr}/hearts/6_broken_heart.png`,
      key:"6_broken_heart"
    },
    {
      path:`${pathStr}/hearts/7_heartpulse.png`,
      key:"7_heartpulse"
    },
    {
      path:`${pathStr}/hearts/8_heartbeat.png`,
      key:"8_heartbeat"
    },
    {
      path:`${pathStr}/hearts/9_two_hearts.png`,
      key:"9_two_hearts"
    },
    {
      path:`${pathStr}/hearts/10_sparkling_heart.png`,
      key:"10_sparkling_heart"
    },
    {
      path:`${pathStr}/hearts/11_revolving_hearts.png`,
      key:"11_revolving_hearts"
    },
    {
      path:`${pathStr}/hearts/12_cupid.png`,
      key:"12_cupid"
    },
    {
      path:`${pathStr}/hearts/13_love_letter.png`,
      key:"13_love_letter"
    },
    {
      path:`${pathStr}/hearts/14_kiss.png`,
      key:"14_kiss"
    },
    {
      path:`${pathStr}/hearts/15_ring.png`,
      key:"15_ring"
    },
    {
      path:`${pathStr}/hearts/16_gem.png`,
      key:"16_gem"
    },
  ]
}
export const symbo={
  text:"符号",
  list:[
    {
      path:`${pathStr}/symbol/1_one.png`,
      key:"1_one"
    },
    {
      path:`${pathStr}/symbol/2_two.png`,
      key:"2_two"
    },
    {
      path:`${pathStr}/symbol/3_three.png`,
      key:"3_three"
    },
    {
      path:`${pathStr}/symbol/4_four.png`,
      key:"4_four"
    },
    {
      path:`${pathStr}/symbol/5_five.png`,
      key:"5_five"
    },
    {
      path:`${pathStr}/symbol/6_six.png`,
      key:"6_six"
    },
    {
      path:`${pathStr}/symbol/7_seven.png`,
      key:"7_seven"
    },
    {
      path:`${pathStr}/symbol/8_eight.png`,
      key:"8_eight"
    },
    {
      path:`${pathStr}/symbol/9_zero.png`,
      key:"9_zero"
    },
    {
      path:`${pathStr}/symbol/10_ten.png`,
      key:"10_ten"
    },
    {
      path:`${pathStr}/symbol/11_x.png`,
      key:"11_x"
    },
    {
      path:`${pathStr}/symbol/12_bangbang.png`,
      key:"12_bangbang"
    },
    {
      path:`${pathStr}/symbol/13_interrobang.png`,
      key:"13_interrobang"
    },
    {
      path:`${pathStr}/symbol/14_exclamation.png`,
      key:"14_exclamation"
    },
    {
      path:`${pathStr}/symbol/15_question.png`,
      key:"15_question"
    },
    
  ]
}